### ISSUE TITLE
Bug: incompatible with Python 3.9

### ISSUE THREAD

**Issue by deparcus** [liske/ifstate#21]
I followed the instructions on https://ifstate.net/, but got errors running `ifstatecli show`.

What I did:
```bash
root@host~# python3 -m venv venv
root@host:~# source venv/bin/activate
(venv) root@host:~# pip install ifstate
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting ifstate
  Downloading https://www.piwheels.org/simple/ifstate/ifstate-1.8.3-py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 557 kB/s
Collecting jsonschema
  Downloading https://www.piwheels.org/simple/jsonschema/jsonschema-4.17.3-py3-none-any.whl (90 kB)
     |████████████████████████████████| 90 kB 16 kB/s
Collecting pyyaml
  Downloading https://www.piwheels.org/simple/pyyaml/PyYAML-6.0-cp39-cp39-linux_armv7l.whl (45 kB)
     |████████████████████████████████| 45 kB 395 kB/s
Collecting pyroute2
  Downloading https://www.piwheels.org/simple/pyroute2/pyroute2-0.7.8-py3-none-any.whl (456 kB)
     |████████████████████████████████| 456 kB 1.1 MB/s
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Downloading https://www.piwheels.org/simple/pyrsistent/pyrsistent-0.19.3-cp39-cp39-linux_armv7l.whl (102 kB)
     |████████████████████████████████| 102 kB 1.2 MB/s
Collecting attrs>=17.4.0
  Downloading https://www.piwheels.org/simple/attrs/attrs-23.1.0-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 691 kB/s
Installing collected packages: pyrsistent, attrs, pyyaml, pyroute2, jsonschema, ifstate
Successfully installed attrs-23.1.0 ifstate-1.8.3 jsonschema-4.17.3 pyroute2-0.7.8 pyrsistent-0.19.3 pyyaml-6.0
(venv) root@host:~# ifstatecli show
Traceback (most recent call last):
  File "/root/venv/bin/ifstatecli", line 5, in <module>
    from ifstate.ifstate import main
  File "/root/venv/lib/python3.9/site-packages/ifstate/ifstate.py", line 3, in <module>
    from libifstate.parser import YamlParser
  File "/root/venv/lib/python3.9/site-packages/libifstate/__init__.py", line 1, in <module>
    from libifstate.exception import LinkDuplicate
  File "/root/venv/lib/python3.9/site-packages/libifstate/exception.py", line 2, in <module>
    from libifstate.util import logger
  File "/root/venv/lib/python3.9/site-packages/libifstate/util.py", line 1, in <module>
    from libifstate.log import logger, IfStateLogging
  File "/root/venv/lib/python3.9/site-packages/libifstate/log.py", line 10, in <module>
    formatter = logging.Formatter('%(bol)s%(prefix)s%(style)s%(message)s%(eol)s', defaults={
TypeError: __init__() got an unexpected keyword argument 'defaults'
(venv) root@host:~#
```

I'm running latest Rasbian 11:
```bash
(venv) root@host:~# cat /etc/debian_version
11.7
(venv) root@host:~# uname -a
Linux host 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux
```

**Comment by liske** [comment]
Can you please provide the output of `pip freeze` and `python --version` inside the venv?

**Comment by liske** [comment]
Thanks, this looks like an issue with python 3.9. My dev machine (Debian bookworm) with python 3.11.2 works fine.

**Comment by liske** [comment]
According to the documentation of [logger.Formatter](https://docs.python.org/3/library/logging.html#logging.Formatter) the `defaults` parameter was introduced in Python 3.10.

Do you need compability with python 3.9?

**Comment by liske** [comment]
Debian bookworm's release is scheduled for 2023-06-10 ;)

I'll look into it and do some testing if I can make it compatble to python 3.9 with a reasonable effort.

**Comment by daks** [comment]
I'm affected by the same bug trying to run on Debian 11 with python 3.9.2-3.
Even with bookworm soon to be released, I won't be able to upgrade before some months so I hope that this bug can be fixed to try this software :)

**Comment by liske** [comment]
The `defaults` parameter for `logging.Formatter()` was absolutely superflous and have been dropped. IfState now works on my Debian 11 machine, again :sweat_smile: 

(ifstate 1.8.4 has been released containing this fix)
